sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: zeW9f2kpbPN4EopwWRVCUWkTFrRr3Rj/Cu2XteU/ZwypZ8Z3iMSB3aTErA2Uha09ea/lgsBVMEwn5ul2PVMLNzleHMTBrL7Z3XaL1MpDikw4GevkO/mmwCV1r++t9xSTCeDhH4UJwI7HVpJ1+NGyMZ/PpGwhYNSMUhL3otaum0E11gIy2mODDebKn4BzV6u/PewSvLfqA4p6Oyu7Z5wPGwCfWjXkiGU1NH82j+oskFrhQHY61h+any7M3VXX24T9WT90ax3SEPorBMKZlwFVKJDfhYWMj9bL2tCOf+uE6xBU+2HaMlJThKsEQTnTz2EscNnhlYkrMNh3Qmr+CcRhCfWbv/a/JSBZCXSi165vkAkYS3bTwDo7osR3IO+rdQEvN8TGay8MS3ya6bUth0I7kPqmig5hJrfzlmqzyKEaN4Zi9mGMLv05+Nx06FNYSrypv0L2W85zNbFd11Hp8GuFfqcGcjr8UrmExu36jqoZ+1axh7EdHl6OAcV0ayXRpCcPrhXl2VaTuirYs4+QRQhN1W3KLvBsu3q4Vvv6GlcZn1jD5dMREZ5EwSDMlwEIbBXl0ONduL6ri1yWaWpknc6vlVnqfXcL+p7oxEcgl7bpO6zji8xQWam/nRVZOce6Iu093AezOUmKI5RWUb6Mu/68fPl8K0vQrE6ZWdCPxyYXHp0=
