sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: iwgUDl0n9ZTbbwprwRlwemFfPMUhcsMGCMui/SedgYQbgJ8GFiEHIwvuFtxMua16oORcEFZ9gUnYwo/CP+6/DnUVUEHpY3x5pK2XdHuVbEjq6rrSz+enrYGuOZADTYyZviu2mhJDfzJbBudw9IFL7Lr37kkfHSV9YTKjybhU09gRZS5IP1Zby+ylxUIEyfOxiwUau4nujXbmRuc+1bLtYH0tLXxccgGPg9Uaou3uUuArWvggiAwvfeDHFbtcRCyxA9ehmY77KXS0hEmIIfRhwEl6Fjce7uKlIxIOmWfgYyIEu0cXWS3Ok1ya283uvl+MWqlbZkAqWVgD5bKyFd8f6bVr2d+KXPyYR6xKiltR1YP/Z6Z/aIuWKC/W87q1R8+wAl0yPEuBRc96Obw04rOpDcw0DCywCP03MOoJS1lJACkjGjvbLNqp86r2uh9BHhn0iEssffBhxxANXIi5fdwUXXra7se53pjbt2jGdtl2NKIiBJUSwUcYrB2mSzYTNArderCkNfWPXIm/UzUdkeWX/2Pc09pXxe6ofjr27b3BGEzgRtdfW780g2dzaTnVmgCwj5m0dACLAkZg8O9+gqPwB9C4kw0nWhD1YU7+92M/9ieGI5GwWJZq6WG/CpIBxOQWyw3rR+HzQl7i04qF7RT5I0dE62YBatfhK0Tnt+2kSkg=
