sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: iYDxp1jv5uT9enBskIK4J3cGbVVCvw9yWyBlJpis7BT6Opee9GMT2ra2TZJrmgSNlkHf0q9ypn9dyTG6Y72XRmNSRHNKSV4gxEaufIyMAqwaz7keyhsdo/4JCpxDYMOxZPfHPZRQYAcKVz6roJ6uaaPa6T67M9JLnZb4T/+HV2/w5/fn6CkDNP4UCeaOayqH/WzYHBeOJuTBEj2+3exeQ1tEankToSkhxJU/PYqSZD/Ymh0YtXDKyuNFzKaSbpFtDNr0vBnt8xTTMJ4oJItaLD4qIaQSQwJsOp7RiCWjfEAyC/9DbFQeVZALp6WNUg5XGIfHQrBU31l+2cGcbdsgy3EBUsgq068RDJXB0AMEBakhWIQKij4T9SgNHUHTOw5mLBXMFg2O83yG3pCLRjtOS6uWDp6jU+iZt4LZl/4ZTEu0pkjIRMIIYRQ738fA4GtKl3vxntkX0bK8gdDWhk3XtzSd8A7u4yHEjCG6XwujQgY8vDWZzwkjmvQw4BCPGbub+y8oYEOoQ68u3YatD8OqC92Gjsz9YKY0nQD3wf9taDj50yn/PKPX88l844HaUGK/zCP8Tr6UlZGCul1bM8ocDWLfK9dz8kCRk+eBqW5YAkg6MJmcshq9YWGrvy6A5Swpprdec7zBjahskLSTm0RcBLVnCTfo1yxsiWLBTG/uzd8=
