sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: 'UKgLlhykzQYWXiE8G4qwzuIlzOzJP5CnYZ3r2IrSUQHaho5ytbZIuzKho2Cgw9O+q7GSTu7RCUdXhkcFD98kKVWZ/ihfuf2CrO+VmBidiQ6YvasREzr7M0lqgQYZvA6Ife2dfobL1tO100ouAt5AzdJ2kGljkRL/r2jvkSibBAG9YALYAXsQoByMPl6zUqqnhYp+nLJNvKjCmI461hwA+P99S4yCimAqUOpLm4RM/lVlixh1z3cmSw8YZKeofs2wcisU07WJUzi0zvGDZLp5LKtHDfpRcLOCyrNNCY9D8gxPulH5LC43gfGT45gVnsdYpbV1mqDVcJd2BJHqfNb0qYjwj4njWMkffh1efYBidfpRyv2ECsrYGLFgl0IqoKMMR2yVljsTYqhUr3USq5QjHVbMDwuDMV0cBoC/FGkrIYjlFnDJw3mP4IBpBlzYEWLOEgaO842LVUIyfrjXnWZ34zfMLCJVyuQpDkkjmKM1cyIFlsUBhrXA8biiO/Oq5ZO/THhxKzG/RbYwO7UjFe7LJjf9LHiKSYcB5dv24MlTlT8McpLnjEp8dLACvDQHHNsohThi2Wt7m3aXr7Y6g+7YEMBC/dS/Y5lxQbgYhhkw0vrY1pxBXwa5V9+rNJUVLzIv1WTLaCZu3sqLkehRsJnQt6S63Yd+t8A9kFgcTkQ9H94='
