sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: wMfbhtPB8AaeFuLBFdgJnZmSrjYtsaDc8Y6+o8NguWRlzA20wmw2zSZqEMQ07Em8k1flMQDcGUwPCvFrqgXYJXMIfFSL22S9mPtOPkmPJ8slCxeVc1F2bXNYMbHzAgEr4qYUcrxOslYepe62Om9vqkxlZWwTc85M23dnRFLhRk+2hJj35tQ+/SpgDmVtuH1d+hlHN0Jinf9e+ATBY3jEtLoh8OoKyqjRIMa3TsPCc5IOkYzOZn4HBLHiQOaMlAMojyKlCV9jqWc1Pgq+zZUxo//2BtgptjikEVOI/ADmkwXAmI35XDGa2vt6iTQgoqsvgPyHQHjixAdF9PFpaEsGfK29cfnD7RjnMs2QSIvOMNVZbtK99pIE8lL2a7iStGD/JXL45kXpwGdv3+Uu9lLzZFizutCC/aqg8l8+b5Z4vFD0usTgu9jnMfshiiVT10X8Lz50hbcckiK/IBDadiSv+4yLNBc9+omGGk7GeNiOc5OEcYI4Ia9a1j5Dm32c/Aru6GNC9kRy5hg5JYjvZ/DyVF7SrDkMRbvdSfjKufMmGz3jykg/TnUvO4y4xfW6Z7Tr3GStOosWYBUgCCBDt4x1/QmeFsMuG/t42Gslc+gt5i4KJjFnynCoRum5rIoexiAgcWY8hcs5w/E9ChCzuj6LZWpnk+P1Soa7yfbp8soFnZE=
