sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: "cy35xpodhdoPFUz0SDkbCTRnO8Fha69LCmOkF+Jqg4eY90d2GeKxvto/A8hejPoZo5N8oEw/0LL6MOGYzilGHha4hTYFL7SU7IP9mBd3i4eiV8Rd8e2WQI3qCHErh3fguBkfgp2WMLztIC4uK4T/nG7Qhh5PGGV4oEaf8Taoqtz7vOPX9cxR3qAnEJY5A7nJ33PrjEOg6qI6fNpv4r2kGeO1cK7K9/+/pVUDLS8xPfpKhZEVjjdg5AZofrnuarz7rE4b5PcJGDceWYARdXCsL/sMK+ntvN7UNy3RkQfb6BrMWZvAM7Hwpou2Xqz5s16VVHVF8bjL42Y9to+R1rZd/6iqMHH1JnBpd/bYFimvXX06A/grbo+u4oiIIKmFO3sC0v3ujjwKreX4F2sVf5bH+EIFkFuU2Uw+taqjs7YN660Dfx86izfc5nn+qOvdAqSXVNROyG2xGPJqxxQYLR0fmKDBRG1ZX+T8EDPVg4QHe6L34FObEBuogX72SmcukxGgMTQYW+s0XqoBFgNauhiPxGQuGY4PWFh0YzhlHCHPt4PH9BvTpmiSplV2rbPN46F9giwLmCK6/1CsUDTC345D3jlCYuf1ni5l2Bob+q/e/NY1eU28Clcf+VvQElEB0TA2hxERKWRWXFHfVbAmu5R5iuXefxihkwNnQQKmUFLf/fY="
