sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: "XVpjNDAAMxD3u7E/t5kI0Aqg2W+XWLa5Ix3a+oe15r14gVzgP2SPMeU0ZgZAnS8Jm7T4BtjVwxiJLcKs7KjDTPRZR8GjJ71AJM/U7IiR9GRXk5DhMK9XQPGhOhn6IXKgES5Fq9xTE5BJHZH+7SrearnCj4CaOEw0v9uHcztIR9GPGvn+RddJJbps4BBo+Z2V90iUbPH1NUyag6cKKXTa3Ahi87X2b+KRbMUwG+QpVvgysT9CJs66MWln0iwAnaPBklhFMwnY9IbWzdBLtxGtw9cvWJzbK7ROeqb4tzSpp/leeJ0XZv15KZaAfsdrWcF3tPgWMIBpLNc2lB2xRWjpUxf/7u7IpxJT07XpWwS2XzHEDMECz0ectsN2QKwehIxPTJzrMQfCy2D2yevPSqABEhSylnlv0lZsZ95FoWSJBvRlXXkznYCGk850vw3IGrs5LmXkwa4bw+bo/RUtYsKvmgBsMY6aGt4pNv0h5cr2vIRI0/32euPbBORMj/+pS8M+9CZpgLkkfXbGFevzmFUo6midIFITg6YbRpZyrLwCIXS5yIyWPVHhDG0PfXxcUSZVOmvdJZ/3zFC5NQ+kUoGw4SdYuzR3O6D0HN8UFqu6WIrPybMx59B1g23+IlUCKgiSNCAB6V+ggIlGldfqc4X2isTn8oJnWBBkchqUwy+NVjg="
