sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: Z4vaSFPoX7s+gFGIUbOWDLlzSjor06AFL8PQiBrlDou1CWmnKAoUEtoHQz+fP8kQXpPgmCOHKsHtZBi1RIsOACQoxvVWZy/7OlrZouBc6K+cmHSbttoJKuMciYIZmAHT74UEBCQPpP3Ry8TRfi8EU6JNhzZllU2Uw88NLAu+4mRLBP4HkGGz3UzXHcIXK6jhy7OpFdhvoiuO54sx5dQai3eh5TRGwXWGwfg+dvuI1W4th/8UhSM2cKK5P9TEPR+D8IcPc/W0Om6AUCVDpE4UfAXz5ManWNlk0PKZKkzqmdHsDKXfBOmNNRE1txdh0GJASZbsErpFxCq4jBafVqB/d8MFXWz8/BMyCHXnT/M+nucRKEjNOYbVX/2a7T+wEV+6RXVd+Vj5aBwGlbLsIMqtF8u3rdR7X1I/g3QkAdqmK7zPobiwwxL4CRQBUHzx5dCR5XpB1Wh49EmhVyPrsupysIE6Xu928vNJAYvYx/a8U29YiLbLD96keILzzrZwxfx7H32U8EO/96zgaDj+vb/wMvwwuxMXY4XEfmFHBmaTyRDRJAV0M3u8Fx9DbAXY6f96kukqKkocIsPrXXJzhrP/3Z+xfXsdWxNV++BgOndGa/9dCzj41Cyf2UVi9RoQvm7LthCCwV5kf2yOP/jw1g03mDX1Iz594CQz3BXaOJGzAG4=
