sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: "E3lbz1+T0z0B2OYoZE87Ml4E6Nv9tey/ZOaUnCaxEZlkW6nawzzK5wO7VjVDtr3luG5JVtp40pmFQkwgdn2JXnGtJm5Q8Vts85W2Z3KJ84sFrIcXxhBvcrKMXlcoqlGuBNbAB0lCP8NTibsFpzRfNGs9QcAhFQC2ayKJl3nz/va3j7X0ABKZ4QUAZNMxPHG0Ce1Qj35LXAtTLjwiPz7GHUSSjumZYOhVFwqXutZFo1oP5ndcduVngNCR1dfKVeGGdVFq10GLdOFzmTXBe9xcK4BtEvto9Gew/jXb7ypNgCF/LEwH5oGCjctpEh0zFMeLwRT0Hf72MZ5qT3vDegmzNLhV7AHttl/ikx1ZbDqbiAChPsIUBRNG4Xvo042+RG5HUA+wjLPZ1GN55eTfuEMi31HFwwl1eeL89OSSSI5omSWa4+CDMZGrhfZ+UkSkBznIUuiXMUNrt4a2yE2M+wk4cQWgWUianqJpvFq2urCO900FY01cweZfxIq1LfdN1NNBUGfUnTgQRmpDiBI2OjM7rnkJKl+ipHxh7+VZ+yL9F3DggHEbs47e/2uW1Q3qrdPr7o3ngksxPczOi9INfn3YF9ERhSEJVwVKV3tOFRmN+NB1ORv3SNrn8lB4mGop90b8Ip74Pl29jDBRBcBB77Vzn/nBbxsYoQmP1b6MvCSu1p4="
